export const REPO_LIST_REQUEST = "REPO_LIST_REQUEST";
export const REPO_LIST_SUCCESS = "REPO_LIST_SUCCESS";
export const REPO_LIST_ERROR = "REPO_LIST_ERROR";
export const REPO_TITLE_ENTER = "REPO_TITLE_ENTER";
export const REPOS_GET_COUNT = "REPOS_GET_COUNT";
export const PAGE_NUMBER_GET = "PAGE_NUMBER_GET";
export const MODEL_OPEN = "MODEL_OPEN";
export const MODEL_CLOSE = "MODEL_CLOSE";
